# Generated by Django 5.1.7 on 2025-05-03 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_librarian_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarian',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
